### ISSUE TITLE
怎么实现define-syntax等?

### ISSUE THREAD

**Issue by zaoqi** [arucil/MyScheme-in-scheme#1]
我不知道怎么实现`define-syntax`等

**Comment by arucil** [comment]
我实现的是R5RS的`syntax-rules` macro，所以姑且认为你问的是`syntax-rules`了哈。
R5RS的macro实现有不少，[eiod.scm](http://petrofsky.org/src/eiod.scm)是一个`eval`函数的实现，里面就包含了`define-syntax`和`syntax-rules`等的实现。
[An Introduction to Macro Expansion Algorithms](https://groups.google.com/forum/#!msg/comp.lang.scheme/6pikEcBrg0Y/p7arhx5XJKgJ)这个系列的文章讲了hygienic macro的实现，作者本来计划是一共有9篇文章的，结果只讲了KFFD和syntactic closure就弃坑了。。不过里面列出的参考文献很有参考价值。
`syntax-rules`的pattern language的实现可以看macro by example这篇paper，或者这两篇博客[Matching Patterns with Scheme](http://blog.theincredibleholk.org/blog/2013/02/11/matching-patterns-with-scheme/)和[Patterns with Ellipses](http://blog.theincredibleholk.org/blog/2013/02/12/patterns-with-ellipses/)，两者是不同的实现，因为R5RS也没有具体说明pattern language的语义。。
其实目前我还只是实现了unhygienic的global macro（没有`let-syntax`和`letrec-syntax`），其他还在摸索中。。

**Comment by zaoqi** [comment]
我正在实现一个Scheme编译器(https://github.com/zaoqi/zscheme)，为了做Minetest(类似Minecraft) Mod.
我认为可以像C一样做一个预处理器。
我找到最接近的是Racket的Macro stepper.
我不能打开eiod.scm。
我找不到`macro by example`

**Comment by arucil** [comment]
sorry，markdown标签用错了。。上面的链接可以打开了。顺便，macro by example在(ftp://www.cs.indiana.edu/pub/techreports/TR206.pdf)。。
scheme的macro确实像c的预处理器一样，不过c的macro是文本替换，scheme的macro是sexp替换。

**Comment by zaoqi** [comment]
但没有从编译器里分离出来，和C不一样

**Comment by zaoqi** [comment]
我实现了卫生宏
通过`macrosym`
当在let,lambda第一次出现一个`macrosym`时，进行了特殊的处理（`newvarid`）
见https://github.com/zaoqi/zscheme

**Comment by arucil** [comment]
scheme的macro也可以做成preprocess的形式。对源程序parse两趟，第一趟处理所有的`defmacro`和宏展开，并把`defmacro`从程序里删去；第二趟再做常规的语法分析。
你这样的`macrosym`实现是宏完全展开之后再转换局部变量，已经太迟了。hygiene是要在`macroexpand`的过程中保持的，在执行`macroexpand`的同时对macro引入的局部变量进行renaming。

**Comment by zaoqi** [comment]
有从编译器里分离出来的吗？
类似`$ cpp`的

**Comment by arucil** [comment]
据我所知，没有

**Comment by zaoqi** [comment]
能从`MyScheme`里分离出来吗？

**Comment by arucil** [comment]
macro expander和evaluator结合得比较紧密，分离不了

**Comment by zaoqi-unsafe** [comment]
有做成preprocess的吗

**Comment by zaoqi-unsafe** [comment]
https://github.com/scheme-requests-for-implementation/srfi-46/blob/master/alexpander.scm
看起来是我要的
